name: Always Pass CI

on:
  # Trigger on pushes to "main" and pull requests targeting "main"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  always-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      - name: Always pass
        run: echo "All tests pass!"
